### ISSUE TITLE
Strict mode unavailable if installing via npm

### ISSUE THREAD

**Issue by gbrolo** [eivindfjeldstad/validate#112]
If you install the package via npm, the "strict" ValidationOption type is not available and unrecognizable if you provide the property "strict" on Schema options object.

index.d.ts
![image](https://user-images.githubusercontent.com/14318182/77486002-3cef8780-6df4-11ea-9b34-31bfc170bd73.png)

Installed version is 5.1.0

**Comment by eivindfjeldstad** [comment]
Version 5.2.0 published
