### ISSUE TITLE
Typescript: Property 'message' does not exist on type 'ValidationError'

### ISSUE THREAD

**Issue by perry-mitchell** [eivindfjeldstad/validate#118]
I've got the following helper function which throws a custom error when validation fails:

```typescript
import VError from "verror";
import Schema from "validate";

function validateObject(obj: Object, schema: Schema) {
    const errors = schema.validate(obj, { typecast: false, strip: false });
    if (errors.length > 0) {
        throw new VError(
            {
                info: {
                    invalidProperties: errors.map(err => err.path),
                    validationErrors: errors.map(err => err.message)
                }
            },
            `Validation failed for object: ${errors[0].message}`
        );
    }
}
```

But typescript throws an error for the `message` property, which apparently isn't present on the `ValidationError` interface.

The `ValidationError` type doesn't mention `message` at all:
https://github.com/eivindfjeldstad/validate/blob/ed3f1ba306ff8a65773886d766213eb35f034127/index.d.ts#L49-L54

**Comment by Divlo** [comment]
Same problem for me, the property message exist but in the TypeScript definition no...
How to deal with it until there is a fix ?

**Comment by Teckden** [comment]
Faced the same problem, I see that there is a PR, is there a chance it can be merged? 
PR: https://github.com/eivindfjeldstad/validate/pull/126
