### ISSUE TITLE
Artifact not published to NPM Registry

### ISSUE THREAD

**Issue by revanth844** [eivindfjeldstad/validate#123]
Dependencies seen in the version uploaded to registry are different from git repo.

https://github.com/eivindfjeldstad/validate/blob/master/package.json
`"dependencies": {    "@eivifj/dot": "^1.0.1",    "component-type": "1.2.1",    "typecast": "0.0.1"  },`

https://www.npmjs.com/package/validate
```
component-type
eivindfjeldstad-dot
typecast
```
<img width="1501" alt="Screenshot 2021-06-01 at 11 19 22" src="https://user-images.githubusercontent.com/5076245/120272782-39df0980-c2cb-11eb-81a6-56f7a55156f5.png">

**Comment by revanth844** [comment]
@eivindfjeldstad FYI

**Comment by eivindfjeldstad** [comment]
Published version 5.2.0
