### ISSUE TITLE
Type shorthand?

### ISSUE THREAD

**Issue by peteruithoven** [eivindfjeldstad/validate#18]
I would love a optional shorthand notation. For example: 
``` javascript
schema({
  username: 'string',
  tags: 'array'
})
```
Instead of:
``` javascript
schema({
  username: {
    type: 'string'
  },
  tags: {
    type: 'array'
  }
})
```
So basically, when there is only a string per path it should be regarded as type requirement.

**Comment by eivindfjeldstad** [comment]
yeah, I agree. I'm a little busy these days, but I'll review a PR
