### ISSUE TITLE
Remove try/catch requires

### ISSUE THREAD

**Issue by badem4o** [eivindfjeldstad/validate#21]
Not sure what the use case for:
https://github.com/eivindfjeldstad/validate/blob/master/lib/schema.js#L5-L11
and this:
https://github.com/eivindfjeldstad/validate/blob/master/lib/property.js#L4-L8
is but they are making this module break under browserify. There are certain browserify transforms that are able to alleviate this problem but from looking at the code there is no immediately apparent reason for this type of try/catch requiring of modules. If that's the case I'll be more than happy to submit a PR with a fix.

**Comment by badem4o** [comment]
So if I'm getting this right, depending on how this package is being installed via npm or via Duo/whatever it uses dependencies that are named differently. Correct?

**Comment by eivindfjeldstad** [comment]
correct

**Comment by izolate** [comment]
Which browserify transforms fix this? I've run into the same problem here.

**Comment by pho3nixf1re** [comment]
Webpack has the same issue but it only throws a warning. I'm assuming I can safely ignore this, but it sure is annoying to see my build bleed warnings.
