### ISSUE TITLE
Browserify compile issues

### ISSUE THREAD

**Issue by lancecarlson** [eivindfjeldstad/validate#25]
Since you're using a node style try... catch require scheme to look up "type" and "dot", browserify doesn't know what is going on. I can work around this using browserify, but do you think it might make sense not to have the try catch require code in there? Why not just try to explicitly require the full package names? "dot" and "type" already have established packages.

**Comment by eivindfjeldstad** [comment]
It's there because of duo and component, neither of which are using npm as their registry. I don't see any way it atm. Have you tried bringing this up in the browserify repo?

**Comment by lancecarlson** [comment]
I have a workaround with browserify but it's not ideal. Also not sure if it makes sense for browserify to account for this type of require pattern necessarily.

**Comment by ktstowell** [comment]
@lancecarlson what was your workaround for Browserify?

**Comment by gone369** [comment]
I just tried using browserify to compile today and got the same issue. There is two ways to solve this. 
1. include [browserify-optional](https://www.npmjs.com/package/browserify-optional) in validate's package.json
2. use [b.ignore](https://github.com/substack/node-browserify#bignorefile)
`browserify(...).ignore("dot").ignore("type")...` 
so example: `browserify('./src/index.js',{}).ignore("type").ignore("dot").bundle()`

**Comment by brennie** [comment]
This also affects building with webpack:

```
WARNING in ./~/validate/lib/schema.js
Module not found: Error: Cannot resolve module 'type' in $CWD/node_modules/validate/lib
 @ ./~/validate/lib/schema.js 5:11-26
```

**Comment by Narkoleptika** [comment]
This is my webpack workaround

```
alias: {
    type: 'component-type',
    dot: 'eivindfjeldstad-dot',
},
```

**Comment by mvastola** [comment]
Thanks, @Narkoleptika!

**Comment by mvastola** [comment]
PS: The author's first-choice npm modules can be used too if you simply add them manually and specify:
```javascript
alias: {
  type: 'type/checks',
  dot: 'dot/index'
}
```

**Comment by eivindfjeldstad** [comment]
Should be fixed now
