### ISSUE TITLE
express framework

### ISSUE THREAD

**Issue by haoyong** [eivindfjeldstad/validate#31]
I use express, and when I validate req.body, error happens.

var schema = require('validate');
var user = schema({
  name: {
    type: 'string',
    required: true,
    message: 'Name is required.'
  },
  email: {
    type: 'string',
    required: true,
    match: /+\@.+\..+/,
    message: 'Email must be valid.'
  }
});

var errors = user.validate(req.body);

error info:
TypeError: obj.hasOwnProperty is not a function
    at Schema.strip (node_modules\validate\lib\schema.js:106:14)
    at Schema.validate (node_modules\validate\lib\schema.js:133:34)

**Comment by eivindfjeldstad** [comment]
This should be fixed now
