### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by sjzamora86** [eivindfjeldstad/validate#36]
Hi,

Thanks for this module! This is awesome!
We are just facing one issue on loading the app in IE. Is there any way that we can use the module in IE.

Thanks! :)

**Comment by eivindfjeldstad** [comment]
You could use [webpack](https://webpack.js.org) and [babel](https://babeljs.io), along with some [polyfills](https://babeljs.io/docs/usage/polyfill/).

**Comment by sjzamora86** [comment]
Thanks for the reply! I managed to make it work by including the module on my webpack config! Thanks
