### ISSUE TITLE
Empty string should be valid for a required string parameter

### ISSUE THREAD

**Issue by jmwilkinson** [eivindfjeldstad/validate#39]
Currently the code:

```
  required(value, ctx, required) {
    if (required === false) return true;
    return value != null && value !== '';
  },
```

causes validation to fail on an empty string. However, an empty string may very well be a valid value on for a required field. This check causes false failures. There should be a separate parameter to require a value not be empty if that intent is required.

**Comment by eivindfjeldstad** [comment]
See #32. In the past, this library has been geared towards validating request bodies etc., where an empty string should be considered invalid. This will probably be changed in the next major version

**Comment by ericmorand** [comment]
For those that needs empty string to be considered as a valid required value, I published a fork that implement that behavior:

https://www.npmjs.com/package/@nightlycommit/validate
