### ISSUE TITLE
How do i avoid validating array property

### ISSUE THREAD

**Issue by sudhakargroup** [eivindfjeldstad/validate#40]
If i have below schema
```
pets: [{
    name: { type: 'string' },
    animal: { enum: ['cat', 'dog']}
  }]
```

current system is validating **name, and animal** correctly. But also validating 

> pets 

and giving some error back, is there any way/configuration to avoid that?

**Comment by eivindfjeldstad** [comment]
what error are you getting, and what object are you validating?

**Comment by sudhakargroup** [comment]
no issue here. thanks.
