### ISSUE TITLE
Mutates the original object

### ISSUE THREAD

**Issue by franciscop-invast** [eivindfjeldstad/validate#42]
Hi, thanks for the library, it seems very useful. It seems from the tests I'm writing that `validate()` is **mutating** the original object, removing the elements that do not match. [See example in sandbox](https://codesandbox.io/s/2zvk68p55n):

```js
import Validator from "validate";

const user = { firstName: "John", lastName: "Smith" };
const UserValidator = new Validator({ firstName: {} });
const log = obj => (document.body.innerHTML += JSON.stringify(obj) + "<br>");

log(user);
const errors = UserValidator.validate(user);
log(user);
log(errors);
```

## Expected result

The user is found with no errors, so `errors` is an empty array and the original object stays the same.

## Actual result

The `errors` is empty as expected; however the original object is modified to remove the property `lastName`. This is a surprising behaviour and searching for "mutate" and "mutation" in the repo brings no result.

## Workaround

Clone the object previous to validation:

```js
const errors = UserValidator.validate(JSON.parse(JSON.stringify(user)));
```

## Extra

`.validate()` implies validation, not mutation nor clean-up. So if you want to change the original object to match the schema, a better options is to provide a function specific for that. Or even the constructor itself:

```js
const User = new Schema({ firstname: {} });  // Create the User schema/validator as normal
const user = User({ firstname: 'John', lastName: 'Smith' });  // Actual properties to be cleaned up
const user = User.clean({ firstname: 'John', lastName: 'Smith' });  // Or maybe this is better
console.log(user);    // { firstname: 'John' }
```

**Comment by eivindfjeldstad** [comment]
You can do
```js
schema.validate(obj, { strip: false })
```

**Comment by franciscop-invast** [comment]
Ah that's really cool, thank you!
