### ISSUE TITLE
Publish compiled version

### ISSUE THREAD

**Issue by franciscop-invast** [eivindfjeldstad/validate#45]
When trying to use `validate` in React (Create-React-App) and build the package:

```bash
Failed to minify the code from this file:

        ./node_modules/validate/lib/schema.js:48
```

You can see the explanation here:

[npm run build fails to minify](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Could a transpiled+minified file be published as well please?

I think the issue might be combining ES6+ features such as `class` with commonjs' `require()` instead of `import`. The proposed solution is to publish the compiled version within the package.

Related: this also breaks CDNs such as Unpkg, a very common and useful CDN for npm modules. This is the default path, that will of course not work since there's `require()` in the file:

> https://unpkg.com/validate@4.3.0/lib/schema.js

So my recommendation is to distribute the minified file and set that as the `main` field in `package.json`, which is the common practice nowadays.

**Comment by franciscop-invast** [comment]
I can make a PR if this is a wanted feature. I would add the compilation needed tools as devDependencies, a npm script such as `"build": "command-to-build"` and the previously mentioned changes.

**Comment by eivindfjeldstad** [comment]
I'm not necessarily against publishing a transpiled version. That said, it's nearly impossible to support all the different build systems out there. It seems like the problem you're experiencing with `create-react-app` has been solved with [this PR](https://github.com/facebook/create-react-app/pull/3776), no? Like I said, not opposed to this, but I really want to avoid introducing additional complexity if it can be avoided:)

**Comment by franciscop-invast** [comment]
I see, that issue is from Jan 2018 so it seems the new Create React App is coming soon. I'll test it out when it's out, thanks!
