### ISSUE TITLE
Errors not contain error message in React Native

### ISSUE THREAD

**Issue by maphongba008** [eivindfjeldstad/validate#53]
My code:
```
import Schema from 'validate';
const post = new Schema({
  title: {
    required: true,
    message: 'Title is required.',
  },
});

const errors = post.validate({});
Logger.log(JSON.stringify(errors));

```
Here's the output:
[{"line":185865,"column":126,"sourceURL":"http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false"}]

**Comment by eivindfjeldstad** [comment]
What version are you using? It's very hard to debug this without having more information. If you could provide a failing test case that would be helpful, although I suspect this is not a bug in `validate`.

**Comment by maphongba008** [comment]
thanks for the great library and for fast reply, I used version 4.4.1, just copy the example from readme and run it.
I think maybe it's incompatible with react-native so I create a node js file to test it, and here's the result:
/**
 * 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0 => []
 **/

/**
 * 4.3.0 => [{"path":"title"}]
 */

/**
 * 4.3.0, 4.4.0, 4.4.1 => [{}]
 */
For version <= 4.2.0, there's no error at all, for 4.3.0, there's 1 error but don't have error message
For some newer version, there's an error but don't have path and error message

**Comment by eivindfjeldstad** [comment]
I believe calling `JSON.stringify` with an `Error` object won't work very well. Something like this might work
```js
errors = schema.validate(obj);

JSON.stringify(errors.map(e => {
  message: e.message,
  path: e.path
}))
```

**Comment by maphongba008** [comment]
thanks for the answer, it works well
Close the issue.
