### ISSUE TITLE
Create typings definition (@types/validate)

### ISSUE THREAD

**Issue by G-Rath** [eivindfjeldstad/validate#59]
I love the idea behind this library, but for some reason WebStorm doesn't seem to think it exists :(

It would be great if this library was [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

I should have some time to have a go at this over the weekend, but wanted to hear your thoughts on the matter (if any).

**Comment by eivindfjeldstad** [comment]
I don't have any objections to this. PR is welcome:)

**Comment by ray0324** [comment]
this has been resolved ,just use `npm install validate`

**Comment by G-Rath** [comment]
Awesome, thanks. 

I actually wrote my own typings, that I'll compare to yours and make a PR if there are any improves, if thats alright with you :)

**Comment by eivindfjeldstad** [comment]
Closing this. Typings should be pretty good at this point
