### ISSUE TITLE
validate object whith order 

### ISSUE THREAD

**Issue by ray0324** [eivindfjeldstad/validate#85]
how about add an order filed to validate Object with destnated order？  such as
```js
new Schema({
  custname: {
    required:true,
    order: 0,
  },
  usersex: {
    required:true,
    order: 1,
  },
  ethnicname: {
    required:true,
    order: 2,
  },
  idno: {
    required:true,
    order:3
  }
})
```
then the errors array should ordered sort by order assoc

**Comment by ibbignerd** [comment]
What is the value in ordering the errors array?

If you want to get a specific key, you could use [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

`errorArray.find((item) => item.path === "custname")`

You could also convert the array to an object using [Array.prototype.reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

```
errorArray.reduce((map, obj) => {
	map[obj.path] = obj;
	return map;
}, {});
```

**Comment by ray0324** [comment]
@ibbignerd  Thanks
