### ISSUE TITLE
Mixed type validation support

### ISSUE THREAD

**Issue by tlvince** [eivindfjeldstad/validate#88]
I have a usecase whereby an object key can be either a string or a nested object, e.g.:

```js
const shorthand = {
  package: 'foo'
}

const longhand = {
  package: {
    name: 'foo',
    version: '1.1.1'
  }
}
```

AFAICT, this is currently unsupported by validate. I've tried:

```js
const isValid = value => typeOf value === 'string' || typeOf value === 'object'

const schema = {
  vertical: {
      required: true,
      use: { isValid },
      name: {
        type: String,
      },
      version: {
        type: String,
      }
    },
  }
}
```

However, adding `name` and `version` causes the `string` variant fail and validating them in the `object` variant doesn't seem to work.

**Comment by eivindfjeldstad** [comment]
There's a new `.properties` rule that you could use:

```js
const schema = new Schema({
  package: {
    required: true,
    use: { isValid },
    properties: {
      name: String,
      version: String
    }
  }
});

```

You could also add a custom validator to verify that `name` and `version` are present if the `package` is an object
